name: "Confirm bug"

on:
 issue_comment:
  types:
    - created

jobs:
  check_comments:
    name: Confirm bug - Comment command
    runs-on: ubuntu-latest
    steps:
      - name: Set-up Comvent
        uses: rytswd/comvent@v0.3
        id: comvent
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config-path: .github/comment-commands.yml

      - name: Checkout
        uses: actions/checkout@v3

      - if: steps.comvent.outputs.confirm-bug != ''
        name: Handle confirmed command - Label
        uses: actions/github-script@v6
        with:
          script: |
            try {
              github.rest.issues.removeLabel({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                name: ['(S1 - Need Confirmation)']
              });
            }
            catch() {
              console.log('Need Confirmation label not found - continuing.');
            }
            finally {
              github.rest.issues.addLabels({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                labels: ['(S2 - Confirmed)']
              });
            }
