name: "Confirm bug"

on:
 issue_comment:
  types:
    - created

jobs:
  check_comments:
    name: Confirm bug - Comment command
    runs-on: ubuntu-latest
    env:
      ISSUE_NUMBER: ${{ github.event.issue.number }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set-up Comvent
        uses: rytswd/comvent@v0.3
        id: comvent
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config-path: .github/comment-commands.yml

      - if: steps.comvent.outputs.confirm-bug != ''
        name: Handle confirmed command - Label
        run: |
          gh issue edit "$ISSUE_NUMBER" --remove-label "(S1 - Need Confirmation)"
          gh issue edit "$ISSUE_NUMBER" --add-label "(S2 - Confirmed)"
