name: JSON Validation

on:
  pull_request:
    paths:
    - '.github/workflows/**'

jobs:
  style-json:
    name: JSON style check

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - name: JSON style check
      run: echo "json style ran"
    - name: Display Corrections
      if: failure()
      run: git diff
