name: "labeler: issue"
on:
  issues:
    types: [opened]
jobs:
  labeler:
    permissions:
      issues: write
    runs-on: ubuntu-latest
    steps:
      - name: check issue title
        uses: actions/github-script@v7
        with:
          script: |
            const title = context.payload.issue.title.toLowerCase();
            const keywords = ['api', 'treesitter', 'ui', 'lsp'];

            const match = keywords.filter(keyword => title.includes(keyword));

            if (match.length !== 0) {
              github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                labels: match
              });
            }
