name: Label First-Time Contributor PRs

on:
  pull_request_target:
    types:
      - opened

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Code-Hex/first-label-interaction@v1.0.1
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          pr-labels: '["new contributor"]'