
# This workflow runs at 23:00 UTC sundays
name: "Pull Tileset Updates"

on:
  push:
    branches:
      - main
  # schedule:
  #   - cron: "0 23 * * sun"

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  pull-updates:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get current timestamp
        id: get-timestamp
        uses: nanzm/get-time-action@v1.1
        with:
          format: 'YYYY-MM-DD'
      - name: "Update Tilesets"
        shell: bash
        run: |
         date +%s > report.txt
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: |
            Routine Tileset updates on ${{ steps.get-timestamp.outputs.time }}
          committer: casswedson <casswedson@users.noreply.github.com>
          author: casswedson <casswedson@users.noreply.github.com>
          branch: tileset-updates
          delete-branch: true
          base: main
          title: Routine Tileset updates on ${{ steps.get-timestamp.outputs.time }}
          body: |
            #### Summary
            None

            Automatic tilesets updates from latest release in
            <https://github.com/I-am-Erk/CDDA-Tilesets>
            <https://github.com/pixel-32/CDDA-tileset>
